### ISSUE TITLE
Filter på programsiden

### ISSUE THREAD

**Issue by tinbeh** [TrondheimDeveloperConference/2019.trondheimdc.no#37]
https://trondheimdc.slack.com/files/U046XHJ2X/FPW249NTG/svid_20191025_210318_1.mp4

Ved valg av f.eks. English + Workshops så får man ingen resultat.

**Comment by computerlove** [comment]
Fikk ikke gjenskapt det som beskrives. La til slik at man ser hva som er aktivt filter
